### ISSUE TITLE
Coordinate descent parameters

### ISSUE THREAD

**Issue by amindh** [GregVial/RelaxedLasso#1]
When we change tol and max_iter in Relaxedlasso and Relaxedlassocv it is not taken into account.
In coordinate_descent.py, these parameters should be added to the fit, _fit, lasso_path, _relasso_path_residues, and relasso_path functions.

**Comment by GregVial** [comment]
When instantiating the RelaxedLasso object, the parameters tol and max_iter are passed to the constructor of the super class (ElasticNet). See code line 628: https://github.com/GregVial/RelaxedLasso/blob/master/relaxed_lasso/coordinate_descent.py


Did you experience evidence that these parameters where not taken into account ? In the scikit-learn lasso impementation, these parameters are not passed to fit, _fit, lasso_path or _path_residuals.
