### ISSUE TITLE
RelaxedLars, RelaxedLasso and cross validation

### ISSUE THREAD

**Issue by amindh** [GregVial/RelaxedLasso#2]
RelaxedLars doesn't seem to work when it is used to estimate coefficients. It give me very high coefficients with error far from the truth. 
Whereas RelaxedLasso can find the right coefficients when given appropriate alpha and theta. 
For both algorithms, the crossvalidation version doesn't seem to work giving coefficients far from the truth

**Comment by GregVial** [comment]
Initial investigations show proper behaviour.
Awaiting further details to debug if required.
